import type { CatalogService } from './types';

/**
 * Indian subscription catalog, 2026 prices. Mirrors the `catalog_services`
 * table (see supabase/migrations) so the app works fully offline; once a
 * Supabase project exists this becomes a synced cache.
 */
export const CATALOG: CatalogService[] = [
  {
    id: 'netflix',
    name: 'Netflix',
    slug: 'netflix',
    category: 'streaming',
    plans: [
      { name: 'Mobile', price_inr: 149, billing_cycle: 'monthly' },
      { name: 'Basic', price_inr: 199, billing_cycle: 'monthly' },
      { name: 'Standard', price_inr: 499, billing_cycle: 'monthly' },
      { name: 'Premium', price_inr: 649, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['netflix', 'nflx'],
    logo_color: '#E50914',
    website: 'https://netflix.com/in',
    popular_rank: 1,
  },
  {
    id: 'hotstar',
    name: 'JioHotstar',
    slug: 'jiohotstar',
    category: 'streaming',
    plans: [
      { name: 'Mobile', price_inr: 149, billing_cycle: 'quarterly' },
      { name: 'Super', price_inr: 299, billing_cycle: 'quarterly' },
      { name: 'Premium', price_inr: 299, billing_cycle: 'monthly' },
      { name: 'Premium Annual', price_inr: 1499, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['hotstar', 'jiohotstar', 'disney\\+?\\s*hotstar', 'star india'],
    logo_color: '#0F1014',
    website: 'https://hotstar.com',
    popular_rank: 2,
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    category: 'music',
    plans: [
      { name: 'Individual', price_inr: 119, billing_cycle: 'monthly' },
      { name: 'Duo', price_inr: 149, billing_cycle: 'monthly' },
      { name: 'Family', price_inr: 179, billing_cycle: 'monthly' },
      { name: 'Individual Annual', price_inr: 1189, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['spotify'],
    logo_color: '#1DB954',
    website: 'https://spotify.com/in',
    popular_rank: 3,
  },
  {
    id: 'jio',
    name: 'Jio Recharge',
    slug: 'jio',
    category: 'telecom',
    plans: [
      { name: '₹349 (28d, 2GB/day)', price_inr: 349, billing_cycle: 'monthly' },
      { name: '₹899 (84d, 2GB/day)', price_inr: 899, billing_cycle: 'quarterly' },
      { name: '₹3,599 Annual', price_inr: 3599, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['\\bjio\\b', 'reliance jio', 'jio prepaid', 'jio recharge'],
    logo_color: '#0A2885',
    website: 'https://jio.com',
    popular_rank: 4,
  },
  {
    id: 'airtel',
    name: 'Airtel Recharge',
    slug: 'airtel',
    category: 'telecom',
    plans: [
      { name: '₹379 (28d, 2GB/day)', price_inr: 379, billing_cycle: 'monthly' },
      { name: '₹979 (84d, 2GB/day)', price_inr: 979, billing_cycle: 'quarterly' },
      { name: '₹3,999 Annual', price_inr: 3999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['airtel', 'bharti airtel'],
    logo_color: '#E40000',
    website: 'https://airtel.in',
    popular_rank: 5,
  },
  {
    id: 'prime',
    name: 'Amazon Prime',
    slug: 'amazon-prime',
    category: 'streaming',
    plans: [
      { name: 'Lite Annual', price_inr: 799, billing_cycle: 'yearly' },
      { name: 'Monthly', price_inr: 299, billing_cycle: 'monthly' },
      { name: 'Annual', price_inr: 1499, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['amazon prime', 'primevideo', 'prime video', 'amzn.*prime'],
    logo_color: '#00A8E1',
    website: 'https://primevideo.com',
    popular_rank: 6,
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    slug: 'youtube-premium',
    category: 'streaming',
    plans: [
      { name: 'Individual', price_inr: 149, billing_cycle: 'monthly' },
      { name: 'Family', price_inr: 299, billing_cycle: 'monthly' },
      { name: 'Individual Annual', price_inr: 1490, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['youtube\\s*premium', 'google\\s*youtube', 'youtubepremium'],
    logo_color: '#FF0000',
    website: 'https://youtube.com/premium',
    popular_rank: 7,
  },
  {
    id: 'swiggy-one',
    name: 'Swiggy One',
    slug: 'swiggy-one',
    category: 'food',
    plans: [
      { name: 'One Lite (3mo)', price_inr: 99, billing_cycle: 'quarterly' },
      { name: 'One (3mo)', price_inr: 399, billing_cycle: 'quarterly' },
      { name: 'One Annual', price_inr: 999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['swiggy\\s*one', 'swiggy.*membership'],
    logo_color: '#FC8019',
    website: 'https://swiggy.com',
    popular_rank: 8,
  },
  {
    id: 'zomato-gold',
    name: 'Zomato Gold',
    slug: 'zomato-gold',
    category: 'food',
    plans: [
      { name: 'Gold (3mo)', price_inr: 99, billing_cycle: 'quarterly' },
      { name: 'Gold Annual', price_inr: 349, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['zomato\\s*gold', 'zomato.*membership', 'eternal.*gold'],
    logo_color: '#E23744',
    website: 'https://zomato.com',
    popular_rank: 9,
  },
  {
    id: 'cult',
    name: 'Cult.fit',
    slug: 'cult-fit',
    category: 'fitness',
    plans: [
      { name: 'Cultpass Home', price_inr: 999, billing_cycle: 'quarterly' },
      { name: 'Cultpass Elite (3mo)', price_inr: 8499, billing_cycle: 'quarterly' },
      { name: 'Cultpass Elite Annual', price_inr: 21999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['cult\\.?fit', 'cultfit', 'curefit', 'cultpass'],
    logo_color: '#FF3278',
    website: 'https://cult.fit',
    popular_rank: 10,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    slug: 'chatgpt-plus',
    category: 'ai',
    plans: [
      { name: 'Go', price_inr: 399, billing_cycle: 'monthly' },
      { name: 'Plus', price_inr: 1999, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['openai', 'chatgpt', 'chat\\s*gpt'],
    logo_color: '#10A37F',
    website: 'https://chatgpt.com',
    popular_rank: 11,
  },
  {
    id: 'claude',
    name: 'Claude Pro',
    slug: 'claude-pro',
    category: 'ai',
    plans: [
      { name: 'Pro', price_inr: 1999, billing_cycle: 'monthly' },
      { name: 'Max', price_inr: 9999, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['anthropic', 'claude\\.ai', '\\bclaude\\b'],
    logo_color: '#D97757',
    website: 'https://claude.ai',
    popular_rank: 12,
  },
  {
    id: 'sonyliv',
    name: 'SonyLIV',
    slug: 'sonyliv',
    category: 'streaming',
    plans: [
      { name: 'Mobile Annual', price_inr: 599, billing_cycle: 'yearly' },
      { name: 'Premium Monthly', price_inr: 299, billing_cycle: 'monthly' },
      { name: 'Premium Annual', price_inr: 999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['sony\\s*liv', 'sonyliv', 'culver max'],
    logo_color: '#7B2BE2',
    website: 'https://sonyliv.com',
    popular_rank: null,
  },
  {
    id: 'zee5',
    name: 'ZEE5',
    slug: 'zee5',
    category: 'streaming',
    plans: [
      { name: 'Premium HD Annual', price_inr: 899, billing_cycle: 'yearly' },
      { name: 'Premium 4K Annual', price_inr: 1499, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['zee5', 'zee\\s*entertainment'],
    logo_color: '#8230C6',
    website: 'https://zee5.com',
    popular_rank: null,
  },
  {
    id: 'jiosaavn',
    name: 'JioSaavn Pro',
    slug: 'jiosaavn-pro',
    category: 'music',
    plans: [
      { name: 'Pro Monthly', price_inr: 99, billing_cycle: 'monthly' },
      { name: 'Pro Annual', price_inr: 499, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['saavn', 'jiosaavn'],
    logo_color: '#2BC5B4',
    website: 'https://jiosaavn.com',
    popular_rank: null,
  },
  {
    id: 'gaana',
    name: 'Gaana Plus',
    slug: 'gaana-plus',
    category: 'music',
    plans: [
      { name: 'Plus Monthly', price_inr: 99, billing_cycle: 'monthly' },
      { name: 'Plus Annual', price_inr: 299, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['gaana'],
    logo_color: '#E72C30',
    website: 'https://gaana.com',
    popular_rank: null,
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    slug: 'apple-music',
    category: 'music',
    plans: [
      { name: 'Student', price_inr: 59, billing_cycle: 'monthly' },
      { name: 'Individual', price_inr: 99, billing_cycle: 'monthly' },
      { name: 'Family', price_inr: 149, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['apple\\s*music', 'apple\\.com/bill', 'itunes'],
    logo_color: '#FA243C',
    website: 'https://music.apple.com',
    popular_rank: null,
  },
  {
    id: 'apple-icloud',
    name: 'iCloud+',
    slug: 'icloud-plus',
    category: 'productivity',
    plans: [
      { name: '50GB', price_inr: 75, billing_cycle: 'monthly' },
      { name: '200GB', price_inr: 219, billing_cycle: 'monthly' },
      { name: '2TB', price_inr: 749, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['icloud'],
    logo_color: '#3693F3',
    website: 'https://icloud.com',
    popular_rank: null,
  },
  {
    id: 'google-one',
    name: 'Google One',
    slug: 'google-one',
    category: 'productivity',
    plans: [
      { name: '100GB', price_inr: 130, billing_cycle: 'monthly' },
      { name: '200GB', price_inr: 210, billing_cycle: 'monthly' },
      { name: '2TB', price_inr: 650, billing_cycle: 'monthly' },
      { name: 'AI Pro', price_inr: 1950, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['google\\s*one', 'google\\s*storage', 'google\\s*\\*?one'],
    logo_color: '#4285F4',
    website: 'https://one.google.com',
    popular_rank: null,
  },
  {
    id: 'vi',
    name: 'Vi Recharge',
    slug: 'vi',
    category: 'telecom',
    plans: [
      { name: '₹365 (28d)', price_inr: 365, billing_cycle: 'monthly' },
      { name: '₹3,799 Annual', price_inr: 3799, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['vodafone', '\\bvi\\b.*recharge', 'vodafone idea'],
    logo_color: '#EE2737',
    website: 'https://myvi.in',
    popular_rank: null,
  },
  {
    id: 'bsnl',
    name: 'BSNL Recharge',
    slug: 'bsnl',
    category: 'telecom',
    plans: [
      { name: '₹199 (30d)', price_inr: 199, billing_cycle: 'monthly' },
      { name: '₹1,999 Annual', price_inr: 1999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['bsnl'],
    logo_color: '#FFB900',
    website: 'https://bsnl.co.in',
    popular_rank: null,
  },
  {
    id: 'zepto-pass',
    name: 'Zepto Pass',
    slug: 'zepto-pass',
    category: 'food',
    plans: [
      { name: 'Pass Monthly', price_inr: 49, billing_cycle: 'monthly' },
      { name: 'Pass Quarterly', price_inr: 149, billing_cycle: 'quarterly' },
    ],
    detection_patterns: ['zepto\\s*pass', 'zepto.*membership'],
    logo_color: '#7C3AED',
    website: 'https://zepto.com',
    popular_rank: null,
  },
  {
    id: 'blinkit',
    name: 'Blinkit (Zomato Gold)',
    slug: 'blinkit-gold',
    category: 'shopping',
    plans: [{ name: 'Via Zomato Gold', price_inr: 349, billing_cycle: 'yearly' }],
    detection_patterns: ['blinkit.*membership'],
    logo_color: '#F8CB46',
    website: 'https://blinkit.com',
    popular_rank: null,
  },
  {
    id: 'flipkart-plus',
    name: 'Flipkart VIP',
    slug: 'flipkart-vip',
    category: 'shopping',
    plans: [{ name: 'VIP (3mo)', price_inr: 99, billing_cycle: 'quarterly' }],
    detection_patterns: ['flipkart\\s*(vip|plus)'],
    logo_color: '#2874F0',
    website: 'https://flipkart.com',
    popular_rank: null,
  },
  {
    id: 'times-prime',
    name: 'Times Prime',
    slug: 'times-prime',
    category: 'shopping',
    plans: [{ name: 'Annual', price_inr: 1199, billing_cycle: 'yearly' }],
    detection_patterns: ['times\\s*prime'],
    logo_color: '#1A1A2E',
    website: 'https://timesprime.com',
    popular_rank: null,
  },
  {
    id: 'aha',
    name: 'aha',
    slug: 'aha',
    category: 'streaming',
    plans: [
      { name: 'Gold Annual', price_inr: 699, billing_cycle: 'yearly' },
      { name: 'Premium Annual', price_inr: 899, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['\\baha\\b.*(video|ott|subscription)', 'arha media'],
    logo_color: '#FF6A2B',
    website: 'https://aha.video',
    popular_rank: null,
  },
  {
    id: 'hoichoi',
    name: 'hoichoi',
    slug: 'hoichoi',
    category: 'streaming',
    plans: [{ name: 'Annual', price_inr: 899, billing_cycle: 'yearly' }],
    detection_patterns: ['hoichoi'],
    logo_color: '#FFD400',
    website: 'https://hoichoi.tv',
    popular_rank: null,
  },
  {
    id: 'audible',
    name: 'Audible',
    slug: 'audible',
    category: 'education',
    plans: [{ name: 'Monthly', price_inr: 199, billing_cycle: 'monthly' }],
    detection_patterns: ['audible'],
    logo_color: '#F8991C',
    website: 'https://audible.in',
    popular_rank: null,
  },
  {
    id: 'kindle-unlimited',
    name: 'Kindle Unlimited',
    slug: 'kindle-unlimited',
    category: 'education',
    plans: [{ name: 'Monthly', price_inr: 169, billing_cycle: 'monthly' }],
    detection_patterns: ['kindle\\s*unlimited'],
    logo_color: '#1F2E3D',
    website: 'https://amazon.in/kindle',
    popular_rank: null,
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium',
    slug: 'linkedin-premium',
    category: 'productivity',
    plans: [
      { name: 'Career', price_inr: 1567, billing_cycle: 'monthly' },
      { name: 'Business', price_inr: 2299, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['linkedin'],
    logo_color: '#0A66C2',
    website: 'https://linkedin.com',
    popular_rank: null,
  },
  {
    id: 'canva',
    name: 'Canva Pro',
    slug: 'canva-pro',
    category: 'productivity',
    plans: [
      { name: 'Pro Monthly', price_inr: 500, billing_cycle: 'monthly' },
      { name: 'Pro Annual', price_inr: 4000, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['canva'],
    logo_color: '#00C4CC',
    website: 'https://canva.com',
    popular_rank: null,
  },
  {
    id: 'adobe-cc',
    name: 'Adobe Creative Cloud',
    slug: 'adobe-cc',
    category: 'productivity',
    plans: [
      { name: 'Photography', price_inr: 797, billing_cycle: 'monthly' },
      { name: 'All Apps', price_inr: 4848, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['adobe'],
    logo_color: '#FA0F00',
    website: 'https://adobe.com/in',
    popular_rank: null,
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    slug: 'microsoft-365',
    category: 'productivity',
    plans: [
      { name: 'Basic Annual', price_inr: 1799, billing_cycle: 'yearly' },
      { name: 'Personal Annual', price_inr: 8699, billing_cycle: 'yearly' },
      { name: 'Family Annual', price_inr: 10999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['microsoft\\s*365', 'msft.*365', 'microsoft.*office'],
    logo_color: '#D83B01',
    website: 'https://microsoft.com/microsoft-365',
    popular_rank: null,
  },
  {
    id: 'gemini',
    name: 'Google AI Pro (Gemini)',
    slug: 'google-ai-pro',
    category: 'ai',
    plans: [{ name: 'AI Pro', price_inr: 1950, billing_cycle: 'monthly' }],
    detection_patterns: ['gemini\\s*(advanced|pro)', 'google\\s*ai\\s*pro'],
    logo_color: '#1B72E8',
    website: 'https://gemini.google.com',
    popular_rank: null,
  },
  {
    id: 'perplexity',
    name: 'Perplexity Pro',
    slug: 'perplexity-pro',
    category: 'ai',
    plans: [{ name: 'Pro', price_inr: 1950, billing_cycle: 'monthly' }],
    detection_patterns: ['perplexity'],
    logo_color: '#20808D',
    website: 'https://perplexity.ai',
    popular_rank: null,
  },
  {
    id: 'pw',
    name: 'Physics Wallah',
    slug: 'physics-wallah',
    category: 'education',
    plans: [{ name: 'Batch (varies)', price_inr: 4999, billing_cycle: 'yearly' }],
    detection_patterns: ['physics\\s*wallah', '\\bpw\\b.*batch'],
    logo_color: '#5A4BDA',
    website: 'https://pw.live',
    popular_rank: null,
  },
  {
    id: 'unacademy',
    name: 'Unacademy Plus',
    slug: 'unacademy-plus',
    category: 'education',
    plans: [{ name: 'Plus Annual', price_inr: 14999, billing_cycle: 'yearly' }],
    detection_patterns: ['unacademy'],
    logo_color: '#08BD80',
    website: 'https://unacademy.com',
    popular_rank: null,
  },
  {
    id: 'gym',
    name: 'Gym Membership',
    slug: 'gym',
    category: 'fitness',
    plans: [
      { name: 'Monthly', price_inr: 1500, billing_cycle: 'monthly' },
      { name: 'Annual', price_inr: 12000, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['gym', 'fitness\\s*(first|centre|center)', "gold'?s gym", 'anytime fitness'],
    logo_color: '#34D399',
    website: '',
    popular_rank: null,
  },
  {
    id: 'newspaper',
    name: 'Newspaper / Magazine',
    slug: 'newspaper',
    category: 'news',
    plans: [{ name: 'Monthly', price_inr: 350, billing_cycle: 'monthly' }],
    detection_patterns: ['times of india', 'hindustan times', 'the hindu', 'indian express', 'toi\\+'],
    logo_color: '#94A3B8',
    website: '',
    popular_rank: null,
  },
  {
    id: 'et-prime',
    name: 'ET Prime',
    slug: 'et-prime',
    category: 'news',
    plans: [{ name: 'Annual', price_inr: 3399, billing_cycle: 'yearly' }],
    detection_patterns: ['et\\s*prime', 'economic\\s*times'],
    logo_color: '#7A0C2E',
    website: 'https://economictimes.com',
    popular_rank: null,
  },
  {
    id: 'xbox-game-pass',
    name: 'Xbox Game Pass',
    slug: 'xbox-game-pass',
    category: 'gaming',
    plans: [
      { name: 'Essential', price_inr: 349, billing_cycle: 'monthly' },
      { name: 'Ultimate', price_inr: 1299, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['xbox', 'game\\s*pass'],
    logo_color: '#107C10',
    website: 'https://xbox.com',
    popular_rank: null,
  },
  {
    id: 'ps-plus',
    name: 'PlayStation Plus',
    slug: 'ps-plus',
    category: 'gaming',
    plans: [
      { name: 'Essential (3mo)', price_inr: 1499, billing_cycle: 'quarterly' },
      { name: 'Essential Annual', price_inr: 4999, billing_cycle: 'yearly' },
    ],
    detection_patterns: ['playstation', 'ps\\s*plus', 'sony.*network'],
    logo_color: '#00439C',
    website: 'https://playstation.com',
    popular_rank: null,
  },
  {
    id: 'tinder',
    name: 'Tinder',
    slug: 'tinder',
    category: 'other',
    plans: [
      { name: 'Plus', price_inr: 199, billing_cycle: 'monthly' },
      { name: 'Gold', price_inr: 549, billing_cycle: 'monthly' },
    ],
    detection_patterns: ['tinder'],
    logo_color: '#FE3C72',
    website: 'https://tinder.com',
    popular_rank: null,
  },
];

export function getCatalogService(idOrSlug: string): CatalogService | undefined {
  return CATALOG.find((s) => s.id === idOrSlug || s.slug === idOrSlug);
}

/** Top-12 grid for onboarding quick-add, ordered by popular_rank. */
export function popularServices(): CatalogService[] {
  return CATALOG.filter((s) => s.popular_rank !== null).sort(
    (a, b) => (a.popular_rank ?? 99) - (b.popular_rank ?? 99),
  );
}

export function searchCatalog(query: string): CatalogService[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  return CATALOG.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.slug.includes(q) ||
      s.category.includes(q),
  );
}
